<a href="https://colab.research.google.com/github/lucasegonzalez/Redes-Neuronales-con-Python-y-Keras/blob/main/Dimensiones_tensores_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Scalar


In [3]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

Vector

In [5]:
x = np.array([42,3,5,3,6,7])
print(x.shape)
x.ndim

(6,)


1

Matrix

In [6]:
x = np.array([[42,3,5,3,6,7],
            [66,54,5,343,6,7]])
             
print(x.shape)
x.ndim

(2, 6)


2

In [ ]:
Tensor

In [8]:
x = np.array([[[42,3,5,3,6,7],
            [66,54,5,343,6,7]],
            [[42,3,5,3,6,7],
            [66,54,5,343,6,7]],
            [[42,3,5,3,6,7],
            [66,54,5,343,6,7]]])
             
print(x.shape)
x.ndim
             


(3, 2, 6)


3

Reshape

In [9]:
x = np.array([[0,1],
              [2,3],
              [4,5],
              [6,7],
              ])
x.shape

(4, 2)

In [10]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [11]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [13]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])